# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import track.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('ISBN', models.CharField(max_length=13, unique=True, validators=[track.models.validate_length13])),
                ('check_out_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('AD', 'Admin'), ('CL', 'Class'), ('PT', 'Parent')], default='ST', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='check_out_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Borrower'),
        ),
    ]
