# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20170502_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_capability',
            field=models.BooleanField(default=False),
        ),
    ]
