# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_book_search_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PR', 'Pc Repair'), ('BO', 'Book Order'), ('CS', 'Cleaning Supplies'), ('FO', 'Furniture Order'), ('O', 'Other')], default=None, max_length=2)),
                ('placed_by', models.ForeignKey(default='AD', on_delete=django.db.models.deletion.CASCADE, to='track.Borrower')),
            ],
        ),
    ]
